## 4.1 Problem Definition
**Selected Dataset:** PlantVillage Dataset (from Kaggle)  
**Dataset Source:** [Kaggle - PlantVillage Dataset](https://www.kaggle.com/datasets/emmareed/plantvillage-dataset)

### Project Overview:
This dataset contains over 54,000 images of healthy and diseased crop leaves across several species. In agriculture, early detection of plant diseases is crucial for food security and reducing pesticide use. This project represents a data investigation into how these diseases are distributed and analyzed within a large-scale image dataset.

### Analytical Questions:
1. **Distribution Analysis:** Which crop species (e.g., Apple, Tomato) are the most and least represented in this dataset? 
   * *Why it matters:* This helps identify if the dataset is biased toward specific crops, which affects how reliable a disease detection model might be for other crops.
2. **Anomaly Detection (NumPy):** Are there any unusual image filenames (outliers) that might indicate data corruption or inconsistent naming conventions? 
   * *Why it matters:* Finding outliers ensures data quality and helps in cleaning before feeding data into a machine learning model.
3. **Relationship Analysis:** Does the variety of diseases found in a specific crop correlate with the total number of images available for that crop?
   * *Why it matters:* To understand if more data leads to discovering more disease types or if certain crops are naturally more prone to diseases.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [6]:
import os
import pandas as pd
import numpy as np


base_path = r'D:\lectures slide\10th semester\Python\Final\Final_Project\dataset\plantvillage dataset\color'

if os.path.exists(base_path):
    all_data = []
    
    for folder in os.listdir(base_path):
        folder_path = os.path.join(base_path, folder)
        
        if os.path.isdir(folder_path):
            for file in os.listdir(folder_path):
                if file.lower().endswith(('.png', '.jpg', '.jpeg')):
                    all_data.append({
                        'Image_Name': file,
                        'Disease_Type': folder
                    })
    
    
    df = pd.DataFrame(all_data)
    print("Successfully loaded data!")
    print(f"Total Unique Image: {len(df)}")
    print("\n1st 5 row:")
    print(df.head())
else:
    print("path not found! kindly check folder path")

Successfully loaded data!
Total Unique Image: 54305

1st 5 row:
                                          Image_Name        Disease_Type
0  00075aa8-d81a-4184-8541-b692b78d398a___FREC_Sc...  Apple___Apple_scab
1  01a66316-0e98-4d3b-a56f-d78752cd043f___FREC_Sc...  Apple___Apple_scab
2  01f3deaa-6143-4b6c-9c22-620a46d8be04___FREC_Sc...  Apple___Apple_scab
3  0208f4eb-45a4-4399-904e-989ac2c6257c___FREC_Sc...  Apple___Apple_scab
4  023123cb-7b69-4c9f-a521-766d7c8543bb___FREC_Sc...  Apple___Apple_scab

In [7]:
df.sample(10)

,Image_Name,Disease_Type
42877,201ada31-7b91-42c1-a245-4d37df0b2c52___Crnl_L....,Tomato___Leaf_Mold
22247,fbdc58af-b7f8-4013-a7b5-0ff97b063f27___Rutg._B...,Peach___Bacterial_spot
26876,9c6155e6-eb4b-4ef9-bcd5-812803cb16d9___RS_LB 3...,Potato___Late_blight
27152,df6898c4-f3a1-4ff2-8f44-3bc45a8d4ec5___RS_LB 3...,Potato___Late_blight
35374,50c95fbd-1d28-47e6-9206-57b601abfa43___RS_L.Sc...,Strawberry___Leaf_scorch
2619,a7fde017-ef6b-44c7-9b1e-825ed048fcce___RS_HL 6...,Apple___healthy
24439,8ba97ec7-5e91-4850-8e87-fe0aaa18aaaf___JR_HL 8...,"Pepper,_bell___healthy"
28569,2e9d001f-3e67-44a3-99bc-52338967cca5___RS_HL 2...,Soybean___healthy
36051,e8f8ed3c-616c-4e45-802f-74c64213174f___RS_L.Sc...,Strawberry___Leaf_scorch
44548,7dd7354c-7c02-4086-8b19-e6d8d4083c29___Matt.S_...,Tomato___Septoria_leaf_spot

In [8]:
disease_counts = df['Disease_Type'].value_counts()
print(disease_counts)

Disease_Type
Orange___Haunglongbing_(Citrus_greening)              5507
Tomato___Tomato_Yellow_Leaf_Curl_Virus                5357
Soybean___healthy                                     5090
Peach___Bacterial_spot                                2297
Tomato___Bacterial_spot                               2127
Tomato___Late_blight                                  1909
Squash___Powdery_mildew                               1835
Tomato___Septoria_leaf_spot                           1771
Tomato___Spider_mites Two-spotted_spider_mite         1676
Apple___healthy                                       1645
Tomato___healthy                                      1591
Blueberry___healthy                                   1502
Pepper,_bell___healthy                                1478
Tomato___Target_Spot                                  1404
Grape___Esca_(Black_Measles)                          1383
Corn_(maize)___Common_rust_                           1192
Grape___Black_rot                                     1180
Corn_(maize)___healthy                                1162
Strawberry___Leaf_scorch                              1109
Grape___Leaf_blight_(Isariopsis_Leaf_Spot)            1076
Cherry_(including_sour)___Powdery_mildew              1052
Potato___Early_blight                                 1000
Potato___Late_blight                                  1000
Tomato___Early_blight                                 1000
Pepper,_bell___Bacterial_spot                          997
Corn_(maize)___Northern_Leaf_Blight                    985
Tomato___Leaf_Mold                                     952
Cherry_(including_sour)___healthy                      854
Apple___Apple_scab                                     630
Apple___Black_rot                                      621
Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot     513
Strawberry___healthy                                   456
Grape___healthy                                        423
Tomato___Tomato_mosaic_virus                           373
Raspberry___healthy                                    371
Peach___healthy                                        360
Apple___Cedar_apple_rust                               275
Potato___healthy                                       152
Name: count, dtype: int64

In [9]:
df.tail()

,Image_Name,Disease_Type
54300,ffb295c9-f14e-4a15-831a-bf905da7fcb6___UF.GRC_...,Tomato___Tomato_Yellow_Leaf_Curl_Virus
54301,ffe08ccc-c55e-4ca2-9234-2906b98b8d05___YLCV_NR...,Tomato___Tomato_Yellow_Leaf_Curl_Virus
54302,ffe996e5-c8dc-47b7-bca2-4fc25e5ac57c___UF.GRC_...,Tomato___Tomato_Yellow_Leaf_Curl_Virus
54303,fff42f1b-7ec4-46e3-9269-45932e63635e___YLCV_GC...,Tomato___Tomato_Yellow_Leaf_Curl_Virus
54304,fff6bf83-797c-4de4-83f7-39b74786fec4___UF.GRC_...,Tomato___Tomato_Yellow_Leaf_Curl_Virus

## 1. Problem Definition
*   **Dataset:** PlantVillage Dataset (Kaggle)
*   **Topic:** This dataset represents various healthy and diseased plant leaves.
*   **Analytical Questions:**
    1. Which plant species/diseases have the highest and lowest representation in the dataset? (Distribution Analysis)
    2. How does the average image filename length vary across different disease categories? (Numerical/Metadata Analysis)
    3. Are there any specific crops (e.g., Tomato, Apple) that are more prone to a wider variety of diseases in this dataset?

In [11]:
#  Data Understanding
print(f"Dataset Shape: {df.shape}")
print(f"Columns: {df.columns.tolist()}")

#  Data Cleaning

initial_count = len(df)
df = df.drop_duplicates()
print(f"Justification: Removed {initial_count - len(df)} duplicate entries to ensure unique image analysis.")


print("\nMissing Values:\n", df.isnull().sum())
print("Justification: Verified there are no null values to avoid errors during aggregation.")


df['Disease_Type'] = df['Disease_Type'].str.replace('___', ' | ')
print("Justification: Replaced '___' with '|' for better readability in visualizations.")

df.head()

Dataset Shape: (54305, 2)
Columns: ['Image_Name', 'Disease_Type']
Justification: Removed 0 duplicate entries to ensure unique image analysis.

Missing Values:
 Image_Name      0
Disease_Type    0
dtype: int64
Justification: Verified there are no null values to avoid errors during aggregation.
Justification: Replaced '___' with '|' for better readability in visualizations.

                                          Image_Name        Disease_Type
0  00075aa8-d81a-4184-8541-b692b78d398a___FREC_Sc...  Apple | Apple_scab
1  01a66316-0e98-4d3b-a56f-d78752cd043f___FREC_Sc...  Apple | Apple_scab
2  01f3deaa-6143-4b6c-9c22-620a46d8be04___FREC_Sc...  Apple | Apple_scab
3  0208f4eb-45a4-4399-904e-989ac2c6257c___FREC_Sc...  Apple | Apple_scab
4  023123cb-7b69-4c9f-a521-766d7c8543bb___FREC_Sc...  Apple | Apple_scab

In [2]:
%pip install pandas numpy matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\88018\appdata\roaming\python\python312\site-packages (3.0.2)
Requirement already satisfied: numpy in c:\users\88018\appdata\roaming\python\python312\site-packages (2.4.4)
Requirement already satisfied: matplotlib in c:\users\88018\appdata\roaming\python\python312\site-packages (3.10.9)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\88018\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\88018\appdata\roaming\python\python312\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\88018\appdata\roaming\python\python312\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\88018\appdata\roaming\python\python312\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\88018\appdata\roaming\python\python312\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\88018\appdata\roaming\python\python312\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\88018\appdata\roaming\python\python312\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in c:\users\88018\appdata\roaming\python\python312\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\88018\appdata\roaming\python\python312\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\users\88018\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip